version: "2.1"
services:
  notecard:
    image: "bh.cr/blues_wireless/notecard-aarch64"
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    expose:
      - "3434"
    privileged: true

  random:
    build: ./example-python

